# Generated by Django 5.0.6 on 2024-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age_group', models.CharField(choices=[('kids', 'Kids'), ('teens', 'Teens'), ('adults', 'Adults')], max_length=10)),
            ],
        ),
    ]
